### PR TITLE
Fix crash when 2catpcha returns a 500 server error

### PR DESCRIPTION
**Pull request by ozeidan**
Occasionally, as documented by 2captcha, the service will return
a response with the content of "500 Internal Server Error". It's unclear
if in this case, the HTTP status code is set properly, as that's not
documented anywhere and this case is hard to reproduce, so the error is
handled by looking at the response body, as it is in the other cases.

Logs and stack trace:
```
Solve geetest
Captcha status: CAPCHA_NOT_READY
Captcha promise: 500 Internal Server Error
Traceback (most recent call last):
  File "flathunt.py", line 111, in <module>
    main()
  File "flathunt.py", line 107, in main
    launch_flat_hunt(config, heartbeat)
  File "flathunt.py", line 55, in launch_flat_hunt
    hunter.hunt_flats()
  File "/home/flathunter/flathunter/flathunter/hunter.py", line 42, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
  File "/home/flathunter/flathunter/flathunter/hunter.py", line 21, in crawl_for_exposes
    return chain(*[searcher.crawl(url, max_pages)
  File "/home/flathunter/flathunter/flathunter/hunter.py", line 21, in <listcomp>
    return chain(*[searcher.crawl(url, max_pages)
  File "/home/flathunter/flathunter/flathunter/abstract_crawler.py", line 142, in crawl
    return self.get_results(url, max_pages)
  File "/home/flathunter/flathunter/flathunter/crawl_immobilienscout.py", line 60, in get_results
    soup = self.get_page(search_url, self.driver, page_no)
  File "/home/flathunter/flathunter/flathunter/crawl_immobilienscout.py", line 120, in get_page
    return self.get_soup_from_url(search_url.format(page_no), driver=driver, captcha_api_key=self.captcha_api_key, checkbox=self.checkbox, afterlogin_string=self.afterlogin_string)
  File "/home/flathunter/flathunter/flathunter/abstract_crawler.py", line 79, in get_soup_from_url
    self.resolvegeetest(driver, captcha_api_key)
  File "/home/flathunter/flathunter/flathunter/abstract_crawler.py", line 185, in resolvegeetest
    recaptcha_answer = recaptcha_answer.split("|", 1)[1]
IndexError: list index out of range
```

### CODE REVIEW

**Comment by jukoson** [comment]
I don't believe this is an appropriate solution. For example, the issue and crash of the script still persists in case that 2captcha reports the following:
[2022/04/08 09:19:14|abstract_crawler.py|DEBUG   ]: Captcha promise: 503 Service Unavailable

How about checking for "OK" in recaptcha_answer before the split ? With that, solved will still False and the loop is executed again.

**Comment by ozeidan** [comment]
Sounds good, I had refactored this part of the code a little bit, I've just pushed it to this PR. I'll update the PR title and desc soon.
I pulled out the 2captcha specific parts into a file and am using backoff for retries. It eventually gives up the captcha solving since I've been running into infinite loops of unsolvable captchas which would result in all other scrapers being blocked too.

**Review by codders — APPROVED** [review]
This looks amazing - thanks for the changes!

**Comment by jukoson** [comment]
One more comment on this PR: The newly required package should also appear in requirements.txt

**Pull request merged**
