### PR TITLE
fix #465: determine Chrome version on Windows

### LINKED ISSUE #465: Unable to determine Chrome version on Windows
Hi,

flathunter is unable to determine the version of Chrome on Windows because
a) Chrome isn't usually in the PATH on Windows and 
b) flathunter tries to get the Chrome version by running it with --version, but Chrome does not respond to this flag on Windows.

PR incoming.

### PR DESCRIPTION
**Pull request by colinemonds**
We can use the `reg` util to access the registry on Windows -- this enables us to find the installed version of Google Chrome, as Chrome does not respond to --version on Windows.

### CODE REVIEW

**Comment by codders** [comment]
Hey @colinemonds ,

This looks great - thank you! The type checker has some issues with the code:
```
/home/runner/work/flathunter/flathunter/flathunter/chrome_wrapper.py
  /home/runner/work/flathunter/flathunter/flathunter/chrome_wrapper.py:12:45 - warning: Unsupported escape sequence in string literal (reportInvalidStringEscapeSequence)
  /home/runner/work/flathunter/flathunter/flathunter/chrome_wrapper.py:12:54 - warning: Unsupported escape sequence in string literal (reportInvalidStringEscapeSequence)
  /home/runner/work/flathunter/flathunter/flathunter/chrome_wrapper.py:12:61 - warning: Unsupported escape sequence in string literal (reportInvalidStringEscapeSequence)
  /home/runner/work/flathunter/flathunter/flathunter/chrome_wrapper.py:[12](https://github.com/flathunters/flathunter/actions/runs/6098394999/job/16548806517?pr=466#step:5:13):68 - warning: Unsupported escape sequence in string literal (reportInvalidStringEscapeSequence)
  /home/runner/work/flathunter/flathunter/flathunter/chrome_wrapper.py:44:31 - error: Object of type "None" cannot be used as iterable value (reportOptionalIterable)
  /home/runner/work/flathunter/flathunter/flathunter/chrome_wrapper.py:46:68 - error: "group" is not a known member of "None" (reportOptionalMemberAccess)
```

You should be able to reproduce those locally by running `pyright`. Please review and adjust the code so that `pyright` is happy.

**Comment by codders** [comment]
Ah. And the code is failing the `ChromeWrapperTest.test_parse_chrome_version` test. Please review and update the test case

**Comment by colinemonds** [comment]
The Chrome version test runs fine on Windows now. Note that a lot of unit tests (mostly anything view-related) seem broken on Windows anyway, or maybe it's just my configuration. Anyhow, I think the code should run fine on either platform.

I also replaced list[str] with List[str]. Sorry, my Python is a bit rusty (by 15 years or so -- `print` is a statement, right?).

**Comment by codders** [comment]
Code coverage always complains - something about the test setup. But thanks again for your efforts here!

**Pull request merged**
