### PR TITLE
Add Title config option to Apprise, add crawler placeholder to title/message config

### PR DESCRIPTION
**Pull request by pomeloy**

### CODE REVIEW

**Comment by codders** [comment]
Hi @pomeloy,

Thanks for your PR. The tests were failing on the `main` branch. I've updated the code there now - can you rebase so that we can retest?

**Comment by pomeloy** [comment]
Did I do this right? 😅

**Comment by codders** [comment]
Yep! Thanks!

It looks like I still have some problems with the tests for the other crawlers. Your changes look fine - I'll merge them with the failing tests. Thanks again for the contribution!

Just as a tip for future PRs - the corrections you made to the whitespace in the config file (removing some of the failing spaces) are very welcome. Probably this is something your editor automatically did for you. Nevertheless it's usually preferred to make changes to whitespace in a separate pull request / commit.

**Review by codders — APPROVED** [review]
Looks good to me - thank you!

**Comment by pomeloy** [comment]
> Just as a tip for future PRs - the corrections you made to the whitespace in the config file (removing some of the failing spaces) are very welcome. Probably this is something your editor automatically did for you. Nevertheless it's usually preferred to make changes to whitespace in a separate pull request / commit.

Thank you! I’ll make sure to split the PRs next time 👍

**Pull request merged**
