### PR TITLE
Add Proxy to all crawlers as an option

### PR DESCRIPTION
**Pull request by mordax777**
Added the Proxy option to all the crawlers if enabled. Maybe some people find this useful..

Also:
* linting
* fix tests
* removed unneeded packages

### CODE REVIEW

**Review by codders — APPROVED** [review]
This looks great - thank you!
Only one thing I notice is that we are ending up with slightly diverging feature-sets. There's the requests-based crawling which supports proxy, and the selenium-based crawling with doesn't (but which does support Javascript). Likewise the Google Cloud deploy doesn't support Selenium (so far). So it's not very easy to work out which config flags work together if you're a new user. I don't really know what to do about that.

**Comment by mordax777** [comment]
When creating this pull request, I had the same thoughts. From what I could gather from the previous projects and the internet, I learned that at one point, the cat and mouse game could go so far that Selenium is unavoidable. My idea was to do this in a transition. Instead of implementing the breaking changes and using Selenium purely on all sites, use it only when required. But I am open to ideas, and maybe we should do some brainstorming and in which direction we want to go.

**Comment by codders** [comment]
I created https://github.com/flathunters/flathunter/projects/9 to track this. I need to spend a bit of time investigating how to embed Chrome in a Google Cloud deployment, but I think it should be possible. Then I'm happy to migrate away from `requests` to `Selenium` for all crawling.

**Comment by mordax777** [comment]
Sounds good! :+1:

**Pull request merged**
