### PR TITLE
added heartbeat message

### PR DESCRIPTION
**Pull request by Manuel030**
Adding an additional optional argument for CLI where users can set the interval time to receive heartbeat messages to check that their bot is alive.

### CODE REVIEW

**Review by codders — COMMENTED** [review]
Thanks so much for this PR - it's really great to get contributions from the community.

Overall I would say I like the direction. In the code you submitted, you have taken a lot of the logic that was in the `sender` packages and dumped it directly in flathunter.py. I think it would be cleaner if the heartbeat functionality had its own module, to keep the main file cleaner.

Would you consider refactoring this?

Thanks!

**Comment by Manuel030** [comment]
Agreed. Let me come back at this a little later :)

**Comment by Manuel030** [comment]
Hi @codders !

What do you think of the new commit? It's cleaner as it separates the heartbeat messaging logic from the main file.

Cheers!

**Review by codders — APPROVED** [review]
Looks good - thanks for the refactor!

**Comment by Manuel030** [comment]
nice. I want to help in development a bit more. any way to communicate?

**Comment by codders** [comment]
For sure - that would be great! You can reach me on Telegram at @c0dd3r5,
and we can make a video call to talk about plans if you have time.

Thanks again for your support

Manuel030 ***@***.***> schrieb am Di., 22. März 2022, 10:05:

**Pull request merged**
