### PR TITLE
Stealthy selenium - Remove selenium's fingerprints

### PR DESCRIPTION
**Pull request by soheilrt**
This PR solves #210.

Changes: Added [undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver) to remove selenium's fingerprints, which allows us to crawl `immobilienscout24` with less pain.

Note: The website may still randomly block requests with captchas, so we can't eliminate captcha solvers. If chrome runs without `--headless` flag, most likely the site will not show any captchas.

### CODE REVIEW

**Review by codders — APPROVED** [review]
Amazing - seems to work for me too. Thanks so much!!

**Comment by codders** [comment]
@squilaSC the driver arguments I use for docker are:
```
                --no-sandbox
                --headless
                --disable-gpu
                --remote-debugging-port=9222
                --disable-dev-shm-usage
                window-size=1024,76
```

Can you try with those and see if that works better?

**Comment by squilaSC** [comment]
@codders Thanks for your input. I made several mistakes I guess. I didn't rebuild the docker image after pulling the repo (sorry for that :D )
After I rebuild the image with the newest commit and your arguments I received this error
```
[2022/09/06 08:36:45|config.py               |INFO    ]: Using config path /config.yaml
[2022/09/06 08:36:45|logging.py              |DEBUG   ]: Settings from config: <flathunter.config.Config object at 0x7f887beed990>
[2022/09/06 08:36:45|abstract_crawler.py     |INFO    ]: Initializing Chrome WebDriver for crawler "CrawlImmobilienscout"...
[2022/09/06 08:36:45|patcher.py              |INFO    ]: patching driver executable /root/.local/share/undetected_chromedriver/0dba8e58d20cec31_chromedriver
Traceback (most recent call last):
  File "flathunt.py", line 110, in <module>
    main()
  File "flathunt.py", line 76, in main
    config.init_searchers()
  File "/usr/src/app/flathunter/config.py", line 96, in init_searchers
    CrawlImmobilienscout(self),
  File "/usr/src/app/flathunter/crawl_immobilienscout.py", line 39, in __init__
    self.driver = self.configure_driver(driver_arguments)
  File "/usr/src/app/flathunter/abstract_crawler.py", line 59, in configure_driver
    driver = uc.Chrome(options=chrome_options)
  File "/usr/local/lib/python3.7/site-packages/undetected_chromedriver/__init__.py", line 408, in __init__
    keep_alive=keep_alive,
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 72, in __init__
    service_log_path, service, keep_alive)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 97, in __init__
    options=options)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/undetected_chromedriver/__init__.py", line 590, in start_session
    capabilities, browser_profile
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:36685
from session not created: This version of ChromeDriver only supports Chrome version 105
Current browser version is 104.0.5112.101
Stacktrace:
```

I then changed the base image from `python:3.7` to `python:3.9` in the Dockerfile and rebuild. Now it is working for me with your arguments for immoscout24

**Comment by soheilrt** [comment]
the chrome and webdriver version MUST be the same. try building the image without cache.

**Pull request merged**
