### PR TITLE
add google chrome as prerequisite

### PR DESCRIPTION
**Pull request by flowni**
I setup a new server where I installed flathunter, but it didn't work without installing google chrome

### CODE REVIEW

**Review by codders — CHANGES_REQUESTED** [review]
Hey there! Thanks for this - I agree it makes sense to add that as a prerequisite.

1. Can you also add a comment to say that Google Chrome is only required for crawling immobilienscout24? The project works fine for the other crawlers without Google Chrome installed.

2. The project works with Google Chrome or with Chromium - can we say that it is either / or?

**Comment by flowni** [comment]
> Hey there! Thanks for this - I agree it makes sense to add that as a prerequisite.
> 
> 1. Can you also add a comment to say that Google Chrome is only required for crawling immobilienscout24? The project works fine for the other crawlers without Google Chrome installed.
> 2. The project works with Google Chrome or with Chromium - can we say that it is either / or?

Hey @codders,
with 2. I totally agree.
With 1. I am still not sure to make it optional as all functionalities of the app should work after installing the prerequisites, what do you think?

**Comment by codders** [comment]
Hey @flowni ,

I think I have a different perspective on prerequisites. The app has a lot of features - it can deploy to google cloud (requires Google Cloud account and GCloud CLI), it can run a webserver (requires Google Cloud account and GCloud CLI), it can do distance calculations (requires Google Maps Distance API token), it can build and run in a docker container (requires docker). I think it makes sense to only ask the user to install the software their need for their use case. But for sure the error messages could be more explicit, for example if someone configures 2captcha without having Google Chrome installed, the app could generate a human-understandable error message on startup (instead of some strange exception).

**Comment by flowni** [comment]
Hey @codders,
I think prerequisites should focus on making the whole app work and infrastructure topics (Docker, GCloud, etc.) are another area for me (maybe an own section 'Deployment').

**Review by codders — APPROVED** [review]

**Pull request merged**
