### PR TITLE
Add possibility to start main.py with config.yml

### PR DESCRIPTION
**Pull request by mrclrchtr**
I just copied the lines from flathunt.py. Without these lines, you cannot specify the config when starting locally.

### CODE REVIEW

**Comment by codders** [comment]
Hey! Thanks for this - it makes sense to add the feature for `main.py`.

Your PR is rejected by the linter - please take a look at the report and fix up the issues there. I would of course prefer if the common code is factored into a module so that we don't write the same thing twice, but that might be a bit of a headache in this case. Your call :)

**Comment by mrclrchtr** [comment]
I will change the code and reopen it :)

**Comment by mrclrchtr** [comment]
I introduced an [argument_parser](https://github.com/flathunters/flathunter/pull/369/commits/31c13d14f3df992ffb5cb2f8a44f969c70bd7b12#diff-1cc24c42aee97509abd124e4f9ad38a0200bb4287e5ac62296b55d09f6ceb3e8) and moved the code. 

This is my first python commit :D I hope it's ok ;)

**Review by codders — APPROVED** [review]
This looks great - thanks for making the extra effort to refactor the code! :)

**Comment by mrclrchtr** [comment]
@codders Unfortunately this is not working as expected with gcloud. 

Today I tried to deploy to app engine. When starting in AE, AE adds its own command line arguments. 

`Running /bin/sh -c exec gunicorn main:app --workers 2 -c /config/gunicorn.py`

There are two problems:
- argparse doesn't know `--workers` and will fail. This can be fixed by using `parser.parse_known_args()[0]`.
- -c clash with ours... we could solve it by changing "config" to something like "flathunter-config" (fc). 

What do you think?

**Comment by mrclrchtr** [comment]
Something like this: https://github.com/mrclrchtr/flathunter/pull/2

**Comment by codders** [comment]
Hi @mrclrchtr ,

Thanks for the report and for looking at this again. I think the changes you made in your new PR are mostly good. I just would like to avoid making backward-incompatible changes to the existing `flathunt.py` script, otherwise a lot of users will have a problem.

Would it also be an option for you to set the gunicorn arguments via the environment:

https://docs.gunicorn.org/en/stable/settings.html#settings

```
GUNICORN_CMD_ARGS="--bind=127.0.0.1 --workers=3" gunicorn app:app
```

Then there might be no conflict? Alternatively, I wonder if it's possible to special-case the `-c` argument for the `main.py` argument parser.

**Comment by mrclrchtr** [comment]
The problem is that I don't set the arguments, but GAE always seems to add them automatically: 

But when I was reading the documentary, I noticed this...
https://cloud.google.com/appengine/docs/standard/python3/runtime
> App Engine will also automatically add the gunicorn to your requirements.txt file if you don't specify the entrypoint field.

I'll add a separate Entrypoint in the app.yaml and test it and get back to you.

**Comment by mrclrchtr** [comment]
Ok, I found a solution with the explicit entrypoint :) I will create a new PR.

**Pull request merged**
