### PR TITLE
Fixed ImageTyperz typo (renamed "ImageTypers" to "ImageTyperz")

### PR DESCRIPTION
**Pull request by alexanderroidl**
- Renamed file ```imagetypers_solver.py``` to ```imagetyperz_solver.py```
- Renamed class- and variable-names accordingly, as well as mentions in comments and logs
- Renamed configuration option "captcha/imagetypers" to "captcha/imagetyperz"
    - Implemented warning for users using old configuration option

### CODE REVIEW

**Review by codders — DISMISSED** [review]
Great - thank you!

**Comment by codders** [comment]
There's a conflict now that the other branch has been merged. Can you rebase?

**Comment by alexanderroidl** [comment]
@codders Thank you! I rebased and added another commit on top, taking care of more linter warnings.

**Review by codders — APPROVED** [review]
Great - thank you!

**Pull request merged**
