### PR TITLE
Change version_main to dynamically get from google-chrome command-line

### PR DESCRIPTION
**Pull request by numb95**
Add a snippet to get the version of google-chrome from CLI instead of the hardcoded one. The Current versioning is not efficient due to rapidly change of Chrome versions.

### CODE REVIEW

**Comment by codders** [comment]
Hey! Thanks for this - this looks cool. One concern I have - the chrome driver supports chromium and google-chrome, and I think also platforms where the browser binary is called just "chrome". Can you make the version check here more generic with regards binary name?

**Comment by numb95** [comment]
@codders Hey,
Thanks for the feedback. I really appreciate that. Let me install the chromium and see what can I do about it to make it more generic.

**Comment by codders** [comment]
Hey @numb95 ,

I made my own PR #254 and integrated your changes into that - I hope that's okay. It should now work for all three different binary names.

Closing this PR as the changes are now merged.

**Comment by numb95** [comment]
@codders 
Thanks for the implementation, 
yours look better than mine.

**Pull request closed without merging**
